apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cp4i-2023.2
  namespace: default
spec:
  finally:
    - name: output-usage
      params:
        - name: SCRIPT
          value: >-
            echo "Platform UI URL:"

            oc get consolelink -l
            app.kubernetes.io/name=ibm-integration-platform-navigator -o json |
            jq '.items[] | select (.spec.href)' | jq '.spec.href'


            echo "Initial admin password:"

            oc -n ibm-common-services get secret platform-auth-idp-credentials
            -o jsonpath='{.data.admin_password}' | base64 -d && echo
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: ibm-pak
  params:
    - default: integration
      description: Namespace to deploy Platform UI
      name: CP4I_NAMESPACE
      type: string
    - default: '2023.2.1'
      description: Version of CP4I Platform UI to deploy
      name: CP4I_VERSION
      type: string
    - default: 'true'
      description: Deploy Asset repository operator
      name: DEPLOY_ASSET_REPOSITORY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy API Connect operator
      name: DEPLOY_API_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy App Connect operator
      name: DEPLOY_APP_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy MQ operator
      name: DEPLOY_MQ_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Streams operator
      name: DEPLOY_EVENT_STREAMS_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Endpoint Management operator
      name: DEPLOY_EVENT_ENDPOINT_MANAGEMENT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy DataPower Gateway operator
      name: DEPLOY_DATAPOWER_GATEWAY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Aspera HSTS operator
      name: DEPLOY_ASPERA_HSTS_OPERATOR
      type: string
    - default: a65ac528-bbca-1425-8d07-fde9e2f1ff70
      name: IBM_ENTITLEMENT_KEY_ID
      type: string
    - default: >-
        https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud
      name: IBM_SECRETS_MANAGER_ENDPOINT
      type: string
  tasks:
    - name: create-namespace
      params:
        - name: SCRIPT
          value: |-
            echo "Creating a new namespace called $(params.CP4I_NAMESPACE)"
            oc apply -f - <<EOF
            apiVersion: v1
            kind: Namespace
            metadata:
              name: $(params.CP4I_NAMESPACE)
            EOF
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: ibm-pak
    
    - name: get-entitlement-key
      params:
        - name: KEY_ID
          value: $(params.IBM_ENTITLEMENT_KEY_ID)
        - name: SECRETS_MANAGER_ENDPOINT_URL
          value: $(params.IBM_SECRETS_MANAGER_ENDPOINT)
      taskRef:
        kind: Task
        name: ibmcloud-secrets-manager-get
      runAfter:
        - create-namespace
    - name: add-global-pull-secret
      params:
        - name: SCRIPT
          value: >-
            mkdir ~/global-pull-secret && cd ~/global-pull-secret

            oc patch --type=merge --patch='{"spec":{"paused":true}}'
            machineconfigpool/master

            oc patch --type=merge --patch='{"spec":{"paused":true}}'
            machineconfigpool/worker

            oc extract secret/pull-secret -n openshift-config --keys=.dockerconfigjson --to=. --confirm
            
            cp .dockerconfigjson .dockerconfigjson.orig

            export CP_AUTH_STRING=$(echo "cp:$(tasks.get-entitlement-key.results.secret-value)" | base64)

            jq ".auths += {\"cp.icr.io\": {\"auth\": \"$CP_AUTH_STRING\"}}" .dockerconfigjson.orig > .dockerconfigjson

            oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson


            oc patch --type=merge --patch='{"spec":{"paused":false}}'
            machineconfigpool/master

            oc patch --type=merge --patch='{"spec":{"paused":false}}'
            machineconfigpool/worker


            oc get mcp

            echo "Wait for check mcp..."

            sleep 30

            #check mcp update status

            echo "Wait for check master node ..."

            oc get mcp --no-headers|grep master

            mcp_master_node=$(oc get mcp --no-headers|grep master|awk '{print
            $4}')

            while [ "${mcp_master_node}" = "True" ]

            do
              oc get mcp --no-headers|grep master
              sleep 10
              mcp_master_node=$(oc get mcp --no-headers|grep master |awk '{print $4}')
            done


            echo "Wait for check worker node ..."

            oc get mcp --no-headers|grep worker

            mcp_worker_node=$(oc get mcp --no-headers|grep worker |awk '{print
            $4}')

            while [ "${mcp_worker_node}" = "True" ]

            do
              oc get mcp --no-headers|grep worker
              sleep 10
              mcp_worker_node=$(oc get mcp --no-headers|grep worker |awk '{print $4}')
            done
      runAfter:
        - get-entitlement-key
      taskRef:
        kind: Task
        name: ibm-pak
    - name: platform-ui-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-integration-platform-navigator
        - name: CASE_VERSION
          value: 7.1.1
        - name: ARCHITECTURE
          value: ''
      runAfter:
        - add-global-pull-secret
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
    - name: platform-ui-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: ibm-integration-platform-navigator
              namespace: openshift-operators
            spec:
              channel: v7.1
              name: ibm-integration-platform-navigator
              source: ibm-integration-platform-navigator-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - platform-ui-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    - name: platform-ui-instance
      params:
        - name: SCRIPT
          value: >-
            echo "Creating a new platform UI instance"

            oc apply -f - <<EOF
            apiVersion: integration.ibm.com/v1beta1
            kind: PlatformNavigator
            metadata:
              name: integration-quickstart
              namespace: integration
            spec:
              license:
                accept: true
                license: L-YBXJ-ADJNSM
              replicas: 1
              version: 2023.2.1
              storage:
                class: ocs-storagecluster-cephfs
            EOF


            echo "Waiting for Platform UI to be deployed..."

            while ! oc wait --for=condition=Ready
            PlatformNavigator/integration-quickstart -n
            $(params.CP4I_NAMESPACE)  2>/dev/null; do sleep 30; done

            echo "Platform UI is deployed"
        - name: VERSION
          value: latest
      runAfter:
        - platform-ui-operator
      taskRef:
        kind: Task
        name: ibm-pak
    - name: copy-ingress-tls
      runAfter:
        - platform-ui-instance
      taskRef:
        kind: Task
        name: ibm-tls-certs
      params:
        - name: namepace
          value: $(params.CP4I_NAMESPACE)
    - name: patch-platform-ui-tls
      runAfter:
        - copy-ingress-tls
      taskRef:
        kind: Task
        name: ibm-pak
      params:
        - name: SCRIPT
          value: >-
            oc patch PlatformNavigator integration-quickstart --type merge --patch '{"spec":{"tls": { "secretName": "custom-tls-secret" }}}' -n $(params.CP4I_NAMESPACE)
    # Asset repository
    - name: asset-repository-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-integration-asset-repository
        - name: CASE_VERSION
          value: 1.5.11
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_ASSET_REPOSITORY_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: asset-repository-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
              name: ibm-integration-asset-repository
              namespace: openshift-operators
            spec:
              channel: v1.5
              installPlanApproval: Automatic
              name: ibm-integration-asset-repository
              source: ibm-integration-asset-repository-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - asset-repository-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # API Connect
    - name: apic-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-apiconnect
        - name: CASE_VERSION
          value: 5.0.0
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_API_CONNECT_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: apic-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/ibm-apiconnect.openshift-operators: ""
              name: ibm-apiconnect
              namespace: openshift-operators
            spec:
              channel: v5.0
              installPlanApproval: Automatic
              name: ibm-apiconnect
              source: ibm-apiconnect-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - apic-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # App Connect
    - name: appconnect-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-appconnect
        - name: CASE_VERSION
          value: 9.1.0
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_APP_CONNECT_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: appconnect-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/ibm-appconnect.openshift-operators: ""
              name: ibm-appconnect
              namespace: openshift-operators
            spec:
              channel: v9.1
              installPlanApproval: Automatic
              name: ibm-appconnect
              source: appconnect-operator-catalogsource
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - appconnect-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # MQ
    - name: mq-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-mq
        - name: CASE_VERSION
          value: 2.4.1
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_MQ_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: mq-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/ibm-mq.openshift-operators: ""
              name: ibm-mq
              namespace: openshift-operators
            spec:
              channel: v2.4
              installPlanApproval: Automatic
              name: ibm-mq
              source: ibmmq-operator-catalogsource
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - mq-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # Event Streams
    - name: es-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-eventstreams
        - name: CASE_VERSION
          value: 3.2.2
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_EVENT_STREAMS_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: es-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/ibm-eventstreams.openshift-operators: ""
              name: ibm-eventstreams
              namespace: openshift-operators
            spec:
              channel: v3.2
              installPlanApproval: Automatic
              name: ibm-eventstreams
              source: ibm-eventstreams
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - es-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # Event Endpoint Management
    - name: eem-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-eventendpointmanagement
        - name: CASE_VERSION
          value: 11.0.2
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_EVENT_ENDPOINT_MANAGEMENT_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: eem-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/ibm-eventendpointmanagement.openshift-operators: ""
              name: ibm-eventendpointmanagement
              namespace: openshift-operators
            spec:
              channel: v11.0
              installPlanApproval: Automatic
              name: ibm-eventendpointmanagement
              source: ibm-eventendpointmanagement-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - eem-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # Datapower
    - name: dp-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-datapower-operator
        - name: CASE_VERSION
          value: 1.7.0
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_DATAPOWER_GATEWAY_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: dp-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/datapower-operator.openshift-operators: ""
              name: datapower-operator-v1.7-ibm-datapower-operator-catalog-openshift-marketplace
              namespace: openshift-operators
            spec:
              channel: v1.7
              installPlanApproval: Automatic
              name: datapower-operator
              source: ibm-datapower-operator-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - dp-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    # Aspera
    - name: aspera-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-datapower-operator
        - name: CASE_VERSION
          value: 1.7.0
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
      when:
        - input: $(params.DEPLOY_ASPERA_HSTS_OPERATOR)
          operator: in
          values: ["true"]
      runAfter:
        - platform-ui-operator
    - name: aspera-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/aspera-hsts-operator.openshift-operators: ""
              name: aspera-hsts-operator
              namespace: openshift-operators
            spec:
              channel: v1.5
              installPlanApproval: Automatic
              name: aspera-hsts-operator
              source: aspera-operators
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - aspera-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    