apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cp4i-2023.2
  namespace: default
spec:
  finally:
    - name: output-usage
      params:
        - name: SCRIPT
          value: >-
            echo "Platform UI URL:"

            oc get consolelink -l
            app.kubernetes.io/name=ibm-integration-platform-navigator -o json |
            jq '.items[] | select (.spec.href)' | jq '.spec.href'


            echo "Initial admin password:"

            oc -n ibm-common-services get secret platform-auth-idp-credentials
            -o jsonpath='{.data.admin_password}' | base64 -d && echo
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: ibm-pak
  params:
    - default: integration
      description: Namespace to deploy Platform UI
      name: CP4I_NAMESPACE
      type: string
    - default: '2023.2.1'
      description: Version of CP4I Platform UI to deploy
      name: CP4I_VERSION
      type: string
    - default: key
      description: IBM Entitlement Key secret key
      name: IBM_ENTITLEMENT_KEY_SECRET_KEY
      type: string
    - default: ibm-entitlement-key
      description: IBM Entitlement Key secret
      name: IBM_ENTITLEMENT_SECRET
      type: string
    - default: 'true'
      description: Deploy Platform UI
      name: DEPLOY_PLATFORM_UI
      type: string
    - default: 'true'
      description: Deploy Asset repository operator (requires Platform UI)
      name: DEPLOY_ASSET_REPOSITORY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy API Connect operator
      name: DEPLOY_API_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy App Connect operator
      name: DEPLOY_APP_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy MQ operator
      name: DEPLOY_MQ_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Streams operator
      name: DEPLOY_EVENT_STREAMS_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Endpoint Management operator
      name: DEPLOY_EVENT_ENDPOINT_MANAGEMENT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy DataPower Gateway operator
      name: DEPLOY_DATAPOWER_GATEWAY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Aspera HSTS operator
      name: DEPLOY_ASPERA_HSTS_OPERATOR
      type: string
    - default: 'true'
      description: Deploy foundational services
      name: DEPLOY_FOUNDATIONAL_SERVICES
      type: string
  tasks:
    - name: platform-ui-operator
      params:
        - name: CASE_NAME
          value: ibm-integration-platform-navigator
        - name: CASE_VERSION
          value: 7.1.1
      taskRef:
        kind: Task
        name: ibm-pak-install-operator-0.1
    - name: api-connect-operator
      params:
        - name: CASE_NAME
          value: ibm-apiconnect
        - name: CASE_VERSION
          value: 5.0.0
      taskRef:
        kind: Task
        name: ibm-pak-install-operator-0.1
    - name: app-connect-operator
      params:
        - name: CASE_NAME
          value: ibm-appconnect
        - name: CASE_VERSION
          value: 9.1.0
      taskRef:
        kind: Task
        name: ibm-pak-install-operator-0.1
    - name: mq-operator
      params:
        - name: CASE_NAME
          value: ibm-mq
        - name: CASE_VERSION
          value: 2.4.1
      taskRef:
        kind: Task
        name: ibm-pak-install-operator-0.1
    