apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cp4i-2023.2
  namespace: default
spec:
  finally:
    - name: output-usage
      params:
        - name: SCRIPT
          value: >-
            echo "Platform UI URL:"

            oc get consolelink -l
            app.kubernetes.io/name=ibm-integration-platform-navigator -o json |
            jq '.items[] | select (.spec.href)' | jq '.spec.href'


            echo "Initial admin password:"

            oc -n ibm-common-services get secret platform-auth-idp-credentials
            -o jsonpath='{.data.admin_password}' | base64 -d && echo
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: ibm-pak
  params:
    - default: integration
      description: Namespace to deploy Platform UI
      name: CP4I_NAMESPACE
      type: string
    - default: '2023.2.1'
      description: Version of CP4I Platform UI to deploy
      name: CP4I_VERSION
      type: string
    - default: key
      description: IBM Entitlement Key secret key
      name: IBM_ENTITLEMENT_KEY_SECRET_KEY
      type: string
    - default: ibm-entitlement-key
      description: IBM Entitlement Key secret
      name: IBM_ENTITLEMENT_SECRET
      type: string
    - default: 'true'
      description: Deploy Asset repository operator
      name: DEPLOY_ASSET_REPOSITORY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy API Connect operator
      name: DEPLOY_API_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy App Connect operator
      name: DEPLOY_APP_CONNECT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy MQ operator
      name: DEPLOY_MQ_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Streams operator
      name: DEPLOY_EVENT_STREAMS_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Event Endpoint Management operator
      name: DEPLOY_EVENT_ENDPOINT_MANAGEMENT_OPERATOR
      type: string
    - default: 'true'
      description: Deploy DataPower Gateway operator
      name: DEPLOY_DATAPOWER_GATEWAY_OPERATOR
      type: string
    - default: 'true'
      description: Deploy Aspera HSTS operator
      name: DEPLOY_ASPERA_HSTS_OPERATOR
      type: string
    - default: 'true'
      description: Deploy foundational services
      name: DEPLOY_FOUNDATIONAL_SERVICES
      type: string
  tasks:
    - name: platform-ui-catalog-source
      params:
        - name: SCRIPT
          value: ''
        - name: CASE_NAME
          value: ibm-integration-platform-navigator
        - name: CASE_VERSION
          value: 7.1.1
        - name: ARCHITECTURE
          value: ''
      taskRef:
        kind: Task
        name: ibm-pak-apply-catalog-source
    - name: platform-ui-operator
      params:
        - name: SUBSCRIPTION
          value: |
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: ibm-integration-platform-navigator
              namespace: openshift-operators
            spec:
              channel: v7.1
              name: ibm-integration-platform-navigator
              source: ibm-integration-platform-navigator-catalog
              sourceNamespace: openshift-marketplace
        - name: SCRIPT
          value: ''
      runAfter:
        - platform-ui-catalog-source
      taskRef:
        kind: Task
        name: apply-olm-subscription-v0.1
    - name: platform-ui-instance
      params:
        - name: SCRIPT
          value: >-
            echo "Creating a new namespace called $(params.CP4I_NAMESPACE)"
            oc apply -f - <<EOF
            apiVersion: v1
            kind: Namespace
            metadata:
              name: $(params.CP4I_NAMESPACE)
            EOF

            echo "Creating a new platform UI instance"

            oc apply -f - <<EOF

            apiVersion: integration.ibm.com/v1beta1

            kind: PlatformNavigator

            metadata:
              name: integration-quickstart
              namespace: $(params.CP4I_NAMESPACE)
            spec:
              license:
                accept: true
                license: L-YBXJ-ADJNSM
              replicas: 2
              storage:
                class: ocs-storagecluster-cephfs
              version: $(params.CP4I_VERSION)
            EOF


            echo "Waiting for Platform UI to be deployed..."

            while ! oc wait --for=condition=Ready
            PlatformNavigator/integration-quickstart -n
            $(params.CP4I_NAMESPACE)  2>/dev/null; do sleep 30; done

            echo "Platform UI is deployed"
        - name: VERSION
          value: latest
      runAfter:
        - platform-ui-operator
      taskRef:
        kind: Task
        name: ibm-pak
    - name: copy-ingress-tls
      runAfter:
        - platform-ui-instance
      taskRef:
        kind: Task
        name: ibm-tls-certs
      params:
        - name: namepace
          value: $(params.CP4I_NAMESPACE)
    - name: patch-platform-ui-tls
      runAfter:
        - copy-ingress-tls
      taskRef:
        kind: Task
        name: ibm-pak
      params:
        - name: SCRIPT
          value: >-
            oc patch PlatformNavigator integration-quickstart --type merge --patch '{"spec":{"tls": { "secretName": "custom-tls-secret" }}}' -n $(params.CP4I_NAMESPACE)
