apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-2023.2-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  pipelineRef:
    name: cp4i-2023.2
  serviceAccountName: pipeline
  timeout: 6h0m0s
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: ibm-pak-manifests
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
          storageClassName: ocs-storagecluster-cephfs
          volumeMode: Filesystem
        status: {}